// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'question.dart';

// **************************************************************************
// JsonLiteralGenerator
// **************************************************************************

const _$capitalsDataJsonLiteral = {
  'Alabama': 'Montgomery',
  'Alaska': 'Juneau',
  'American Samoa': 'Pago Pago',
  'Arizona': 'Phoenix',
  'Arkansas': 'Little Rock',
  'California': 'Sacramento',
  'Colorado': 'Denver',
  'Connecticut': 'Hartford',
  'Delaware': 'Dover',
  'Florida': 'Tallahassee',
  'Georgia': 'Atlanta',
  'Guam': 'Hagåtña',
  'Hawaii': 'Honolulu',
  'Idaho': 'Boise',
  'Illinois': 'Springfield',
  'Indiana': 'Indianapolis',
  'Iowa': 'Des Moines',
  'Kansas': 'Topeka',
  'Kentucky': 'Frankfort',
  'Louisiana': 'Baton Rouge',
  'Maine': 'Augusta',
  'Maryland': 'Annapolis',
  'Massachusetts': 'Boston',
  'Michigan': 'Lansing',
  'Minnesota': 'Saint Paul',
  'Mississippi': 'Jackson',
  'Missouri': 'Jefferson City',
  'Montana': 'Helana',
  'Nebraska': 'Lincoln',
  'Nevada': 'Carson City',
  'New Hampshire': 'Concord',
  'New Jersey': 'Trenton',
  'New Mexico': 'Santa Fe',
  'New York': 'Albany',
  'North Carolina': 'Raleigh',
  'North Dakota': 'Bismark',
  'Northern Mariana Islands': 'Saipan',
  'Ohio': 'Columbus',
  'Oklahoma': 'Oklahoma City',
  'Oregon': 'Salem',
  'Pennsylvania': 'Harrisburg',
  'Puerto Rico': 'San Juan',
  'Rhode Island': 'Providence',
  'South Carolina': 'Columbia',
  'South Dakota': 'Pierre',
  'Tennessee': 'Nashville',
  'Texas': 'Austin',
  'US Virgin Islands': 'Charlotte Amalie',
  'Utah': 'Salt Lake City',
  'Vermont': 'Montpelier',
  'Virginia': 'Richmond',
  'Washington': 'Olympia',
  'West Virginia': 'Charleston',
  'Wisconsin': 'Madison',
  'Wyoming': 'Cheyenne'
};
